### ISSUE TITLE
Bookmarks inside folders is not working as expected

### ISSUE THREAD

**Issue by joaopalmeiro** [pxlprfct/bookmarked#32]
Hi! 👋 

I was using `bookmarked` to create a bookmarks file where all of them should be inside a folder. However, I think there is a problem with file generation, as bookmarks are not imported in Chrome and Edge (at least) inside a folder as expected.

Looking at the code and the [Netscape Bookmark File Format specification](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)), I think the problem is with the order of elements in [this function](https://github.com/pxlprfct/bookmarked/blob/main/src/formatters/html.ts#L11): `<DL><P>` must come after `<DT>` and not before. I manually changed the order in a generated file and it worked as expected.

What do you think? Thanks! 😄

**Comment by pxlprfct** [comment]
Heya 👋

I'll try and have a look at this tonight and push out a new version. Not quite sure how I missed this!

Thanks for the link to the spec too - I'll go through and add anything else I'm missing.

Thanks so much, 
Ollie

**Comment by joaopalmeiro** [comment]
Perfect, thanks! Let me know if I can help in any way.
